"""365-bird rotation for the TRMNL Bird of the Day panel.

Each ordinary year shows every bird exactly once in a deterministic shuffled order.
Leap day uses a separate bonus bird.
"""

from datetime import date
import random

BIRDS = [
    {"name": 'Shoebill', "scientific": 'Balaeniceps rex', "fact": 'Can stand statue-still for long periods before striking at lungfish and other prey.'},
    {"name": 'Atlantic Puffin', "scientific": 'Fratercula arctica', "fact": 'Its colourful breeding-season bill fades to a duller grey after the breeding season.'},
    {"name": 'Resplendent Quetzal', "scientific": 'Pharomachrus mocinno', "fact": 'Males grow spectacular tail coverts that can extend far beyond the body.'},
    {"name": 'Secretarybird', "scientific": 'Sagittarius serpentarius', "fact": 'It hunts snakes and other prey on foot, delivering powerful downward kicks.'},
    {"name": 'Kākāpō', "scientific": 'Strigops habroptilus', "fact": 'This flightless nocturnal parrot has males that make deep booming calls from display bowls.'},
    {"name": 'Great Potoo', "scientific": 'Nyctibius grandis', "fact": 'By day it freezes upright on a branch, looking remarkably like a broken stump.'},
    {"name": 'Southern Cassowary', "scientific": 'Casuarius casuarius', "fact": 'Its casque grows on top of the head and may help with signalling or moving through vegetation.'},
    {"name": 'Blue-footed Booby', "scientific": 'Sula nebouxii', "fact": 'Males show off their bright blue feet in an exaggerated high-stepping courtship dance.'},
    {"name": 'Hoatzin', "scientific": 'Opisthocomus hoazin', "fact": 'Young chicks have functional claws on their wings that help them climb through branches.'},
    {"name": 'Superb Fairywren', "scientific": 'Malurus cyaneus', "fact": 'Breeding males transform into vivid blue-and-black plumage while females remain brownish.'},
    {"name": 'King Penguin', "scientific": 'Aptenodytes patagonicus', "fact": 'Parents may leave a chick fasting for weeks while they make long feeding trips at sea.'},
    {"name": 'Toco Toucan', "scientific": 'Ramphastos toco', "fact": 'Its enormous bill is surprisingly lightweight because the interior has a foam-like structure.'},
    {"name": 'Kea', "scientific": 'Nestor notabilis', "fact": 'This alpine New Zealand parrot is famously curious and often investigates objects with its beak.'},
    {"name": 'Bearded Vulture', "scientific": 'Gypaetus barbatus', "fact": 'It specialises in eating bones and drops large ones onto rocks to smash them open.'},
    {"name": 'Satin Bowerbird', "scientific": 'Ptilonorhynchus violaceus', "fact": 'Males decorate bowers with mostly blue objects to impress visiting females.'},
    {"name": 'Greater Sage-Grouse', "scientific": 'Centrocercus urophasianus', "fact": 'Males inflate paired chest sacs and make extraordinary popping sounds on communal display grounds.'},
    {"name": 'Andean Condor', "scientific": 'Vultur gryphus', "fact": 'Its wingspan can exceed three metres, helping it soar for hours with little flapping.'},
    {"name": 'Harpy Eagle', "scientific": 'Harpia harpyja', "fact": 'Its massive talons are adapted for seizing arboreal mammals such as sloths and monkeys.'},
    {"name": 'Sword-billed Hummingbird', "scientific": 'Ensifera ensifera', "fact": 'Its bill can be longer than its body, an extreme adaptation for deep tubular flowers.'},
    {"name": 'Bee Hummingbird', "scientific": 'Mellisuga helenae', "fact": 'At roughly two grams, it is the smallest living bird species.'},
    {"name": 'Magnificent Frigatebird', "scientific": 'Fregata magnificens', "fact": 'Courting males inflate a huge scarlet throat pouch like a shiny red balloon.'},
    {"name": 'Greater Roadrunner', "scientific": 'Geococcyx californianus', "fact": 'It can sprint after lizards, insects and even small rattlesnakes on the ground.'},
    {"name": 'Common Kingfisher', "scientific": 'Alcedo atthis', "fact": 'Its brilliant blue appearance is produced largely by feather structure rather than blue pigment.'},
    {"name": 'Laughing Kookaburra', "scientific": 'Dacelo novaeguineae', "fact": 'Family groups often join in a loud laughing chorus to advertise their territory.'},
    {"name": 'Southern Ground Hornbill', "scientific": 'Bucorvus leadbeateri', "fact": 'Family groups raise very few young, and a chick may remain dependent for years.'},
    {"name": 'Great Hornbill', "scientific": 'Buceros bicornis', "fact": 'The female seals herself inside a tree cavity while nesting, leaving only a narrow feeding slit.'},
    {"name": 'Helmeted Hornbill', "scientific": 'Rhinoplax vigil', "fact": 'Unlike most hornbills, its casque is largely solid rather than hollow.'},
    {"name": 'Rhinoceros Hornbill', "scientific": 'Buceros rhinoceros', "fact": 'Its huge upturned casque sits above an already enormous bill.'},
    {"name": 'African Grey Parrot', "scientific": 'Psittacus erithacus', "fact": 'Studies have shown remarkable abilities in vocal learning, categorisation and numerical concepts.'},
    {"name": 'Palm Cockatoo', "scientific": 'Probosciger aterrimus', "fact": 'Males manufacture drumsticks from branches and beat them against hollow trees during displays.'},
    {"name": 'Sulphur-crested Cockatoo', "scientific": 'Cacatua galerita', "fact": 'Its dramatic yellow crest can spring upright when the bird is excited or alarmed.'},
    {"name": 'Galah', "scientific": 'Eolophus roseicapilla', "fact": 'These pink-and-grey cockatoos sometimes perform playful aerial acrobatics in large flocks.'},
    {"name": 'Rainbow Lorikeet', "scientific": 'Trichoglossus moluccanus', "fact": 'Its brush-tipped tongue is specialised for licking nectar and pollen from flowers.'},
    {"name": 'Eclectus Parrot', "scientific": 'Eclectus roratus', "fact": 'Males are bright green while females are predominantly red and blue-purple.'},
    {"name": 'Hyacinth Macaw', "scientific": 'Anodorhynchus hyacinthinus', "fact": "It is the world's largest flying parrot by length, with an exceptionally powerful bill."},
    {"name": 'Scarlet Macaw', "scientific": 'Ara macao', "fact": 'Pairs can remain together for years and often fly side by side.'},
    {"name": 'Sun Parakeet', "scientific": 'Aratinga solstitialis', "fact": 'Its blazing yellow, orange and red plumage makes adults look almost flame-coloured.'},
    {"name": 'Budgerigar', "scientific": 'Melopsittacus undulatus', "fact": 'Wild flocks can rapidly move across arid Australia following rainfall and fresh seed growth.'},
    {"name": 'Cockatiel', "scientific": 'Nymphicus hollandicus', "fact": 'Its expressive crest changes position with mood and attention.'},
    {"name": "Pesquet's Parrot", "scientific": 'Psittrichas fulgidus', "fact": 'Its bare dark face helps keep sticky fruit pulp away from facial feathers.'},
    {"name": 'Southern Lapwing', "scientific": 'Vanellus chilensis', "fact": 'Bold black, white and grey plumage, red eyes and a sharp wing spur give this noisy South American lapwing plenty of character.'},
    {"name": 'Vulturine Guineafowl', "scientific": 'Acryllium vulturinum', "fact": 'Its cobalt body, striped hackles and bare head make it look almost unreal.'},
    {"name": 'Helmeted Guineafowl', "scientific": 'Numida meleagris', "fact": 'Its spotted plumage is covered in neat white dots, while the head is mostly bare.'},
    {"name": 'Indian Peafowl', "scientific": 'Pavo cristatus', "fact": "The famous 'tail' display is actually formed mostly by elongated upper-tail coverts."},
    {"name": 'Green Peafowl', "scientific": 'Pavo muticus', "fact": 'Both sexes are more green and elongated in appearance than the familiar Indian Peafowl.'},
    {"name": 'Great Argus', "scientific": 'Argusianus argus', "fact": 'Males spread enormous patterned wing feathers into a spectacular circular courtship display.'},
    {"name": 'Golden Pheasant', "scientific": 'Chrysolophus pictus', "fact": 'Males combine a golden crest, orange cape, red body and boldly barred tail.'},
    {"name": "Lady Amherst's Pheasant", "scientific": 'Chrysolophus amherstiae', "fact": "The male's black-and-white cape can be raised into a dramatic fan during courtship."},
    {"name": "Temminck's Tragopan", "scientific": 'Tragopan temminckii', "fact": 'Displaying males reveal an electric-blue throat lappet patterned with vivid red markings.'},
    {"name": 'Himalayan Monal', "scientific": 'Lophophorus impejanus', "fact": 'Male feathers shimmer through metallic green, blue, copper and purple depending on the light.'},
    {"name": 'Wild Turkey', "scientific": 'Meleagris gallopavo', "fact": 'A displaying male can rapidly change the colour of bare skin on his head and neck.'},
    {"name": 'Ocellated Turkey', "scientific": 'Meleagris ocellata', "fact": 'Its tail is covered with blue-green eye spots and its head has bright orange nodules.'},
    {"name": 'Greater Prairie-Chicken', "scientific": 'Tympanuchus cupido', "fact": 'Males inflate orange neck sacs and produce low booming notes during elaborate dances.'},
    {"name": 'Rock Ptarmigan', "scientific": 'Lagopus muta', "fact": 'Its plumage changes seasonally, becoming largely white in winter for camouflage on snow.'},
    {"name": 'Willow Ptarmigan', "scientific": 'Lagopus lagopus', "fact": 'Feathered feet act like natural snowshoes in its cold northern habitat.'},
    {"name": 'Malleefowl', "scientific": 'Leipoa ocellata', "fact": 'It incubates eggs inside a giant mound heated by decomposing vegetation and sunlight.'},
    {"name": 'Australian Brushturkey', "scientific": 'Alectura lathami', "fact": 'Males constantly adjust huge nest mounds to keep buried eggs near the right temperature.'},
    {"name": 'Victoria Crowned Pigeon', "scientific": 'Goura victoria', "fact": 'This giant pigeon wears an extraordinary lace-like blue crest tipped in white.'},
    {"name": 'Nicobar Pigeon', "scientific": 'Caloenas nicobarica', "fact": 'Its metallic neck hackles and white tail make it one of the most striking pigeons.'},
    {"name": 'Spinifex Pigeon', "scientific": 'Geophaps plumifera', "fact": 'Its tall pointed crest gives this small Australian pigeon a wonderfully punk appearance.'},
    {"name": 'Pink-necked Green Pigeon', "scientific": 'Treron vernans', "fact": 'Males combine a pink neck, orange breast and green body while feeding quietly in fruiting trees.'},
    {"name": 'Namaqua Dove', "scientific": 'Oena capensis', "fact": 'Its extremely long tapered tail makes this tiny dove look almost swallow-like in flight.'},
    {"name": "Victoria's Riflebird", "scientific": 'Ptiloris victoriae', "fact": 'A displaying male curves iridescent wings around a female like a shimmering theatrical cape.'},
    {"name": 'Magnificent Riflebird', "scientific": 'Ptiloris magnificus', "fact": 'Males perform highly choreographed displays using glossy black wings and an iridescent breast shield.'},
    {"name": "Wilson's Bird-of-Paradise", "scientific": 'Cicinnurus respublica', "fact": 'The male has a bare blue crown patterned like tiny wrinkles and curled violet tail wires.'},
    {"name": 'King Bird-of-Paradise', "scientific": 'Cicinnurus regius', "fact": 'Tiny males wave emerald-tipped tail wires during an elaborate hanging courtship display.'},
    {"name": 'Greater Bird-of-Paradise', "scientific": 'Paradisaea apoda', "fact": 'Males raise long golden flank plumes over their backs while displaying high in rainforest trees.'},
    {"name": 'Twelve-wired Bird-of-Paradise', "scientific": 'Seleucidis melanoleucus', "fact": 'Males have twelve strange wire-like flank feathers used to brush females during courtship.'},
    {"name": 'Ribbon-tailed Astrapia', "scientific": 'Astrapia mayeri', "fact": 'Males grow two extraordinary white tail feathers that can be several times their body length.'},
    {"name": 'King of Saxony Bird-of-Paradise', "scientific": 'Pteridophora alberti', "fact": 'Males carry two absurdly long head wires lined with tiny enamel-blue flags.'},
    {"name": 'Superb Bird-of-Paradise', "scientific": 'Lophorina superba', "fact": 'During display the male transforms into a black oval with an electric-blue breast shield.'},
    {"name": 'Blue Bird-of-Paradise', "scientific": 'Paradisaea rudolphi', "fact": 'Males hang upside down while spreading blue flank plumes into a shimmering fan.'},
    {"name": 'Western Parotia', "scientific": 'Parotia sefilata', "fact": 'The male performs a ballerina-like dance inside a carefully cleaned display court.'},
    {"name": 'Long-wattled Umbrellabird', "scientific": 'Cephalopterus penduliger', "fact": 'Males possess a long feathered throat wattle that can hang far below the body.'},
    {"name": 'Amazonian Umbrellabird', "scientific": 'Cephalopterus ornatus', "fact": 'Its towering crest and inflatable throat sac help males produce deep booming calls.'},
    {"name": 'Guianan Cock-of-the-rock', "scientific": 'Rupicola rupicola', "fact": 'Males gather at leks and compete while wearing brilliant orange plumage and a semicircular crest.'},
    {"name": 'Andean Cock-of-the-rock', "scientific": 'Rupicola peruvianus', "fact": "The male's huge disk-like crest partly hides its bill when seen from the side."},
    {"name": 'Three-wattled Bellbird', "scientific": 'Procnias tricarunculatus', "fact": 'Males have three dangling facial wattles and one of the loudest calls in the bird world.'},
    {"name": 'White Bellbird', "scientific": 'Procnias albus', "fact": 'Its explosive call has been measured among the loudest bird vocalisations ever recorded.'},
    {"name": 'Bare-throated Bellbird', "scientific": 'Procnias nudicollis', "fact": 'Males are brilliant white with a vivid bare turquoise throat and a metallic hammer-like call.'},
    {"name": 'Capuchinbird', "scientific": 'Perissocephalus tricolor', "fact": 'Its bizarre low call has been compared to a distant chainsaw or mooing cow.'},
    {"name": 'Club-winged Manakin', "scientific": 'Machaeropterus deliciosus', "fact": 'Males produce musical tones by rubbing specially modified wing feathers together at high speed.'},
    {"name": 'Red-capped Manakin', "scientific": 'Ceratopipra mentalis', "fact": "Males perform a rapid backwards 'moonwalk' along branches during courtship."},
    {"name": 'Wire-tailed Manakin', "scientific": 'Pipra filicauda', "fact": 'Males have fine wire-like extensions projecting from their tail feathers.'},
    {"name": 'Long-tailed Manakin', "scientific": 'Chiroxiphia linearis', "fact": 'Two males may cooperate in a synchronised courtship dance, although only one usually mates.'},
    {"name": 'Blue-backed Manakin', "scientific": 'Chiroxiphia pareola', "fact": 'Males can perform coordinated displays with partners on traditional courtship perches.'},
    {"name": 'Golden-headed Manakin', "scientific": 'Ceratopipra erythrocephala', "fact": 'Displaying males make lightning-fast jumps and wing snaps on small forest branches.'},
    {"name": 'Great Blue Turaco', "scientific": 'Corythaeola cristata', "fact": 'The largest turaco has a towering crest, a heavy yellow-tipped bill and a remarkably long tail.'},
    {"name": "Bower's Shrike-thrush", "scientific": 'Colluricincla boweri', "fact": 'This Australian rainforest songbird is named for its range rather than bower-building behaviour.'},
    {"name": 'Regent Bowerbird', "scientific": 'Sericulus chrysocephalus', "fact": 'Males paint the inside of their bowers with plant material and saliva.'},
    {"name": 'Great Bowerbird', "scientific": 'Chlamydera nuchalis', "fact": 'Males arrange pale objects around avenue bowers to create forced-perspective visual illusions.'},
    {"name": 'Flame Bowerbird', "scientific": 'Sericulus ardens', "fact": 'The male is so intensely orange-red that its plumage can look almost luminous.'},
    {"name": 'Spotted Bowerbird', "scientific": 'Chlamydera maculata', "fact": 'Males collect bones, shells, glass and other pale treasures around their bowers.'},
    {"name": 'Western Bowerbird', "scientific": 'Chlamydera guttata', "fact": 'Its bower decorations can include stones, shells, bones and human-made objects.'},
    {"name": 'Superb Lyrebird', "scientific": 'Menura novaehollandiae', "fact": 'Males can imitate other birds and many environmental sounds with astonishing accuracy.'},
    {"name": "Albert's Lyrebird", "scientific": 'Menura alberti', "fact": 'Unlike its famous relative, the male lacks the spectacular lyre-shaped outer tail feathers.'},
    {"name": 'Common Hill Myna', "scientific": 'Gracula religiosa', "fact": 'Its powerful vocal-learning ability allows it to imitate human speech with remarkable clarity.'},
    {"name": 'Common Raven', "scientific": 'Corvus corax', "fact": 'Ravens can solve complex problems and have been observed playing in snow and wind.'},
    {"name": 'New Caledonian Crow', "scientific": 'Corvus moneduloides', "fact": 'It manufactures hooked tools from twigs and leaves to extract hidden prey.'},
    {"name": 'Hawaiian Crow', "scientific": 'Corvus hawaiiensis', "fact": 'This critically endangered crow can use tools, a rare ability among birds.'},
    {"name": 'Rook', "scientific": 'Corvus frugilegus', "fact": 'Rooks nest communally in noisy colonies known as rookeries.'},
    {"name": 'Eurasian Magpie', "scientific": 'Pica pica', "fact": 'Magpies cache food and show sophisticated spatial memory when recovering hidden items.'},
    {"name": 'Blue Jay', "scientific": 'Cyanocitta cristata', "fact": 'It can mimic the calls of hawks, sometimes causing other birds to scatter.'},
    {"name": "Steller's Jay", "scientific": 'Cyanocitta stelleri', "fact": 'Its dramatic black crest contrasts with a deep blue body across western North America.'},
    {"name": 'Green Jay', "scientific": 'Cyanocorax yncas', "fact": 'Its combination of green back, blue head and yellow-green tail is unusually colourful for a corvid.'},
    {"name": 'White-crested Turaco', "scientific": 'Tauraco leucolophus', "fact": 'Its brilliant white crest contrasts with a colourful face, green body and flashes of crimson in the wings.'},
    {"name": 'Curl-crested Jay', "scientific": 'Cyanocorax cristatellus', "fact": 'Its stiff curled forehead feathers form a wonderfully distinctive crest.'},
    {"name": 'White-throated Magpie-Jay', "scientific": 'Calocitta formosa', "fact": 'Its enormously long tail can be longer than the rest of its body.'},
    {"name": 'Taiwan Blue Magpie', "scientific": 'Urocissa caerulea', "fact": 'Family groups travel through forests in striking blue processions with long graduated tails.'},
    {"name": 'Red-billed Blue-Magpie', "scientific": 'Urocissa erythroryncha', "fact": 'Its electric-blue body, red bill and extremely long tail make it unmistakable.'},
    {"name": 'Eurasian Jay', "scientific": 'Garrulus glandarius', "fact": 'It buries thousands of acorns and forgotten caches can help regenerate oak woodland.'},
    {"name": "Clark's Nutcracker", "scientific": 'Nucifraga columbiana', "fact": 'It can remember the locations of thousands of seed caches across a huge landscape.'},
    {"name": 'Spotted Nutcracker', "scientific": 'Nucifraga caryocatactes', "fact": 'It stores pine seeds in many hidden caches and retrieves them months later.'},
    {"name": 'Black-capped Chickadee', "scientific": 'Poecile atricapillus', "fact": "It can add more 'dee' notes to its alarm call when a predator poses greater danger."},
    {"name": 'Tufted Titmouse', "scientific": 'Baeolophus bicolor', "fact": 'It sometimes plucks hair from sleeping mammals to use as soft nest lining.'},
    {"name": 'Long-tailed Tit', "scientific": 'Aegithalos caudatus', "fact": 'Its stretchy nest is woven from moss, cobwebs and feathers and expands as chicks grow.'},
    {"name": 'Bearded Reedling', "scientific": 'Panurus biarmicus', "fact": 'Adult males sport black facial markings that look like an extravagant drooping moustache.'},
    {"name": 'Penduline Tit', "scientific": 'Remiz pendulinus', "fact": 'It builds a beautifully woven hanging nest with a tubular entrance.'},
    {"name": 'European Robin', "scientific": 'Erithacus rubecula', "fact": 'Robins can be fiercely territorial despite their famously friendly garden image.'},
    {"name": 'Bluethroat', "scientific": 'Luscinia svecica', "fact": 'Males wear a brilliant blue throat patch that can contain red or white central markings.'},
    {"name": 'Siberian Rubythroat', "scientific": 'Calliope calliope', "fact": "The male's vivid ruby-red throat contrasts sharply with its otherwise subtle plumage."},
    {"name": 'Japanese Robin', "scientific": 'Larvivora akahige', "fact": "Its rich orange face and breast make it one of Japan's most distinctive forest songbirds."},
    {"name": 'White-rumped Shama', "scientific": 'Copsychus malabaricus', "fact": 'Its rich, varied song has made it famous as an accomplished mimic and songster.'},
    {"name": 'Oriental Magpie-Robin', "scientific": 'Copsychus saularis', "fact": 'Males sing from prominent perches and can incorporate imitations into their songs.'},
    {"name": 'Common Nightingale', "scientific": 'Luscinia megarhynchos', "fact": 'Its celebrated song includes an extraordinary variety of whistles, trills and repeated phrases.'},
    {"name": 'Varied Thrush', "scientific": 'Ixoreus naevius', "fact": 'Its eerie single-note whistles are a characteristic sound of Pacific Northwest forests.'},
    {"name": 'Blue Rock-Thrush', "scientific": 'Monticola solitarius', "fact": 'Adult males can appear a remarkable slate-blue while perched on rocky cliffs and buildings.'},
    {"name": 'Grandala', "scientific": 'Grandala coelicolor', "fact": 'Adult males are an almost surreal deep blue and form flocks in high Himalayan country.'},
    {"name": 'American Robin', "scientific": 'Turdus migratorius', "fact": 'It can detect earthworms using visual and other cues while cocking its head over lawns.'},
    {"name": 'Common Blackbird', "scientific": 'Turdus merula', "fact": 'Males often deliver rich, fluting songs from rooftops and treetops around dawn.'},
    {"name": 'Fieldfare', "scientific": 'Turdus pilaris', "fact": 'Colonies may collectively mob predators and even bombard them with droppings.'},
    {"name": 'Redwing', "scientific": 'Turdus iliacus', "fact": 'Its rusty-red underwing patch flashes brightly when the bird takes flight.'},
    {"name": 'Song Thrush', "scientific": 'Turdus philomelos', "fact": 'It often repeats each musical phrase several times before switching to the next.'},
    {"name": 'Mistle Thrush', "scientific": 'Turdus viscivorus', "fact": "Its habit of singing in wild weather earned it the old nickname 'stormcock'."},
    {"name": 'Common Starling', "scientific": 'Sturnus vulgaris', "fact": 'Huge winter flocks can form spectacular synchronised aerial displays called murmurations.'},
    {"name": 'Superb Starling', "scientific": 'Lamprotornis superbus', "fact": 'Its metallic blue-green back contrasts with a bright orange belly and white chest band.'},
    {"name": 'Violet-backed Starling', "scientific": 'Cinnyricinclus leucogaster', "fact": 'Adult males have a startling violet-purple back above clean white underparts.'},
    {"name": 'Golden-breasted Starling', "scientific": 'Lamprotornis regius', "fact": 'Turquoise, violet, green and gold-orange combine in one extraordinarily colourful bird.'},
    {"name": 'Rosy Starling', "scientific": 'Pastor roseus', "fact": 'Adults in breeding plumage are glossy black and pale pink with a shaggy crest.'},
    {"name": 'Bali Myna', "scientific": 'Leucopsar rothschildi', "fact": 'Its snowy white plumage is offset by bright blue bare skin around the eyes.'},
    {"name": 'Common Myna', "scientific": 'Acridotheres tristis', "fact": 'Highly adaptable and intelligent, it thrives in many human-modified environments.'},
    {"name": 'Red-billed Oxpecker', "scientific": 'Buphagus erythrorynchus', "fact": 'It rides on large African mammals and feeds on ticks, wounds and other animal matter.'},
    {"name": 'Yellow-billed Oxpecker', "scientific": 'Buphagus africanus', "fact": 'Specialised feet and stiff tails help it cling to moving mammals while feeding.'},
    {"name": 'Wallcreeper', "scientific": 'Tichodroma muraria', "fact": 'It flutters over sheer cliffs, flashing crimson-and-black wings like a giant butterfly.'},
    {"name": 'Eurasian Nuthatch', "scientific": 'Sitta europaea', "fact": 'It can climb head-first down tree trunks, a trick most tree-climbing birds cannot manage.'},
    {"name": 'Red-breasted Nuthatch', "scientific": 'Sitta canadensis', "fact": 'It smears sticky conifer resin around its nest entrance, apparently helping deter intruders.'},
    {"name": 'Brown Creeper', "scientific": 'Certhia americana', "fact": 'It spirals upward around tree trunks before flying down to begin again near the base.'},
    {"name": 'Spotted Creeper', "scientific": 'Salpornis spilonota', "fact": 'Its mottled plumage makes it exceptionally difficult to spot against tree bark.'},
    {"name": 'Greater Racket-tailed Drongo', "scientific": 'Dicrurus paradiseus', "fact": 'Its bizarre outer tail feathers end in dangling racket-shaped tips.'},
    {"name": 'Fork-tailed Drongo', "scientific": 'Dicrurus adsimilis', "fact": 'It can imitate alarm calls of other species and sometimes uses them to steal food.'},
    {"name": 'Hair-crested Drongo', "scientific": 'Dicrurus hottentottus', "fact": 'Fine curled feathers on its head give it a slightly tousled appearance.'},
    {"name": 'Black Drongo', "scientific": 'Dicrurus macrocercus', "fact": 'Despite its modest size, it aggressively attacks much larger birds that enter its territory.'},
    {"name": 'Common Iora', "scientific": 'Aegithina tiphia', "fact": 'Males perform fluttering courtship displays that reveal flashes of white in the plumage.'},
    {"name": 'Golden Oriole', "scientific": 'Oriolus oriolus', "fact": "The male's brilliant yellow body is surprisingly hard to spot among sunlit green leaves."},
    {"name": 'Black-naped Oriole', "scientific": 'Oriolus chinensis', "fact": 'Its golden-yellow body is crossed by a bold black stripe through the eye and nape.'},
    {"name": 'African Golden Oriole', "scientific": 'Oriolus auratus', "fact": 'The male glows yellow against woodland foliage but often remains hidden high in the canopy.'},
    {"name": 'Black-and-red Broadbill', "scientific": 'Cymbirhynchus macrorhynchos', "fact": 'It builds a large hanging nest suspended over water or open ground.'},
    {"name": 'Long-tailed Broadbill', "scientific": 'Psarisomus dalhousiae', "fact": 'Its green body, yellow face and blue crown give it an almost toy-like appearance.'},
    {"name": 'Silver-breasted Broadbill', "scientific": 'Serilophus lunatus', "fact": 'Its soft silver, chestnut and blue colouring is unusually delicate for a tropical broadbill.'},
    {"name": 'Black-and-yellow Broadbill', "scientific": 'Eurylaimus ochromalus', "fact": 'The enormous turquoise bill contrasts with black, yellow and pink plumage.'},
    {"name": 'African Broadbill', "scientific": 'Smithornis capensis', "fact": 'Males create a loud mechanical trill with specially modified wing feathers during display flights.'},
    {"name": 'Velvet Asity', "scientific": 'Philepitta castanea', "fact": 'Breeding males develop bright green facial wattles above velvety black plumage.'},
    {"name": "Schlegel's Asity", "scientific": 'Philepitta schlegeli', "fact": 'Males develop vivid blue and green facial skin during the breeding season.'},
    {"name": 'Sunbird Asity', "scientific": 'Neodrepanis coruscans', "fact": 'Its long curved bill and iridescent colours make this Madagascan bird resemble a tiny sunbird.'},
    {"name": 'Spoon-billed Sandpiper', "scientific": 'Calidris pygmaea', "fact": 'Its tiny bill ends in a unique spoon-shaped tip, unlike that of any other sandpiper.'},
    {"name": 'Malachite Sunbird', "scientific": 'Nectarinia famosa', "fact": 'Breeding males shimmer metallic green and carry two long tail streamers.'},
    {"name": 'Beautiful Sunbird', "scientific": 'Cinnyris pulchellus', "fact": 'The male combines iridescent green, red, yellow and elongated central tail feathers.'},
    {"name": 'Purple Sunbird', "scientific": 'Cinnyris asiaticus', "fact": 'Breeding males can look black until sunlight reveals intense blue-purple iridescence.'},
    {"name": 'Palestine Sunbird', "scientific": 'Cinnyris osea', "fact": 'Its metallic plumage can shift from blue to green and purple as the viewing angle changes.'},
    {"name": 'Scarlet-chested Sunbird', "scientific": 'Chalcomitra senegalensis', "fact": 'Males wear a glowing scarlet chest patch against glossy dark plumage.'},
    {"name": 'Greater Double-collared Sunbird', "scientific": 'Cinnyris afer', "fact": 'Its breast shows two contrasting coloured bands beneath a metallic green head.'},
    {"name": 'Red-legged Honeycreeper', "scientific": 'Cyanerpes cyaneus', "fact": 'Breeding males combine electric blue plumage with striking bright red legs.'},
    {"name": 'Green Honeycreeper', "scientific": 'Chlorophanes spiza', "fact": 'Males are turquoise-green with a black hood, while females are bright leaf-green.'},
    {"name": 'Purple Honeycreeper', "scientific": 'Cyanerpes caeruleus', "fact": 'Its long curved bill is ideal for probing flowers and fruit, while males are vivid purple-blue.'},
    {"name": 'Bananaquit', "scientific": 'Coereba flaveola', "fact": 'It often pierces flowers at the base to steal nectar without pollinating them.'},
    {"name": 'Vermilion Flycatcher', "scientific": 'Pyrocephalus rubinus', "fact": 'Adult males are brilliantly red, often making conspicuous fluttering display flights.'},
    {"name": 'Scissor-tailed Flycatcher', "scientific": 'Tyrannus forficatus', "fact": 'Its extraordinarily long forked tail opens and closes during agile aerial manoeuvres.'},
    {"name": 'Fork-tailed Flycatcher', "scientific": 'Tyrannus savana', "fact": 'Long black tail streamers trail behind it during acrobatic flights after insects.'},
    {"name": 'Royal Flycatcher', "scientific": 'Onychorhynchus coronatus', "fact": 'When excited it can reveal a spectacular fan-shaped red-and-blue crest normally kept folded.'},
    {"name": 'Great Kiskadee', "scientific": 'Pitangus sulphuratus', "fact": "Its loud name-like call sounds roughly like 'kis-ka-DEE'."},
    {"name": 'Red-crowned Crane', "scientific": 'Grus japonensis', "fact": 'Pairs perform elegant synchronised dances of bows, leaps and wing-spreading displays.'},
    {"name": 'Cock-tailed Tyrant', "scientific": 'Alectrurus tricolor', "fact": 'Males carry strange curled black tail feathers during the breeding season.'},
    {"name": 'Streamer-tailed Tyrant', "scientific": 'Gubernetes yetapa', "fact": 'Its long forked tail and bold black-white-rufous plumage make it conspicuous in marshy grasslands.'},
    {"name": 'Many-colored Rush Tyrant', "scientific": 'Tachuris rubrigastra', "fact": 'This tiny marsh bird packs yellow, red, green, blue, black and white into one body.'},
    {"name": 'Black-and-white Monjita', "scientific": 'Heteroxolmis dominicanus', "fact": 'Its stark monochrome plumage makes it look unusually formal for a flycatcher.'},
    {"name": 'Paradise Tanager', "scientific": 'Tangara chilensis', "fact": 'Its plumage combines lime green, turquoise, red and black in startling blocks of colour.'},
    {"name": 'Seven-colored Tanager', "scientific": 'Tangara fastuosa', "fact": 'True to its name, this Brazilian endemic carries an extraordinary mixture of vivid colours.'},
    {"name": 'Green-headed Tanager', "scientific": 'Tangara seledon', "fact": 'Its turquoise-green head contrasts with black, orange and blue-violet body patches.'},
    {"name": 'Swallow Tanager', "scientific": 'Tersina viridis', "fact": 'Males are brilliant turquoise-blue and often nest in holes in banks or cliffs.'},
    {"name": 'Red-necked Tanager', "scientific": 'Tangara cyanocephala', "fact": 'A bright red neck ring separates its blue head from green-and-black body plumage.'},
    {"name": 'Golden Tanager', "scientific": 'Tangara arthus', "fact": 'Its predominantly golden-yellow plumage is patterned with contrasting black markings.'},
    {"name": 'Blue-gray Tanager', "scientific": 'Thraupis episcopus', "fact": 'Its soft blue-grey colouring makes it a familiar garden bird across much of tropical America.'},
    {"name": 'Brazilian Tanager', "scientific": 'Ramphocelus bresilia', "fact": 'Adult males are an intense scarlet-red with black wings and a pale silvery bill.'},
    {"name": 'Silver-beaked Tanager', "scientific": 'Ramphocelus carbo', "fact": "The male's velvety dark-red plumage is set off by a conspicuously pale lower bill."},
    {"name": 'Flame-faced Tanager', "scientific": 'Tangara parzudakii', "fact": 'Its fiery orange face grades into yellow, green and black across the body.'},
    {"name": 'Gilt-edged Tanager', "scientific": 'Tangara cyanoventris', "fact": 'Turquoise-blue underparts and golden-green edging make this Atlantic Forest bird exceptionally ornate.'},
    {"name": 'Scarlet Tanager', "scientific": 'Piranga olivacea', "fact": 'Breeding males are brilliant scarlet with jet-black wings, then moult into yellow-green.'},
    {"name": 'Western Tanager', "scientific": 'Piranga ludoviciana', "fact": 'Breeding males combine a red-orange head, yellow body and black wings.'},
    {"name": 'Painted Bunting', "scientific": 'Passerina ciris', "fact": 'Adult males look almost unreal, combining blue, red and green in sharply contrasting patches.'},
    {"name": 'Indigo Bunting', "scientific": 'Passerina cyanea', "fact": 'Males appear intensely blue even though their feathers contain no blue pigment.'},
    {"name": 'Lazuli Bunting', "scientific": 'Passerina amoena', "fact": 'The male combines a turquoise-blue head with a cinnamon breast and white belly.'},
    {"name": 'Gouldian Finch', "scientific": 'Erythrura gouldiae', "fact": 'Wild birds occur with naturally different head colours, including black, red and yellow.'},
    {"name": 'Zebra Finch', "scientific": 'Taeniopygia guttata', "fact": 'Young males learn their songs by listening to adult tutors during a sensitive developmental period.'},
    {"name": 'Java Sparrow', "scientific": 'Padda oryzivora', "fact": 'Its massive pink bill and neat grey-black-white plumage give it a distinctive toy-like appearance.'},
    {"name": 'Owl Finch', "scientific": 'Taeniopygia bichenovii', "fact": "Its round black facial outline is responsible for the wonderfully appropriate name 'owl finch'."},
    {"name": 'Strawberry Finch', "scientific": 'Amandava amandava', "fact": 'Breeding males turn bright red and become sprinkled with tiny white spots.'},
    {"name": 'Red-cheeked Cordon-bleu', "scientific": 'Uraeginthus bengalus', "fact": 'Males add vivid crimson cheek patches to otherwise powder-blue and brown plumage.'},
    {"name": 'Purple Grenadier', "scientific": 'Granatina ianthinogaster', "fact": 'Males combine violet-blue underparts with a chestnut back and vivid red bill.'},
    {"name": 'Cut-throat Finch', "scientific": 'Amadina fasciata', "fact": 'Adult males have a dramatic red band across the throat that looks almost painted on.'},
    {"name": 'Long-tailed Finch', "scientific": 'Poephila acuticauda', "fact": 'Its elegant pointed tail and colourful bill make this Australian grassfinch especially distinctive.'},
    {"name": 'Diamond Firetail', "scientific": 'Stagonopleura guttata', "fact": 'Black, white and fiery red markings combine with white-spotted black flanks.'},
    {"name": 'Red-browed Finch', "scientific": 'Neochmia temporalis', "fact": 'A vivid red eyebrow and rump brighten this otherwise olive-grey Australian finch.'},
    {"name": 'European Goldfinch', "scientific": 'Carduelis carduelis', "fact": 'Its fine pointed bill is well suited to extracting tiny seeds from thistles and teasels.'},
    {"name": 'American Goldfinch', "scientific": 'Spinus tristis', "fact": 'Males moult into brilliant yellow breeding plumage, then become much duller in winter.'},
    {"name": 'Hawfinch', "scientific": 'Coccothraustes coccothraustes', "fact": 'Its enormous bill can crack hard cherry stones to reach the seed inside.'},
    {"name": 'Pine Grosbeak', "scientific": 'Pinicola enucleator', "fact": 'Males can be rosy-red while females and young birds are mostly grey and yellowish.'},
    {"name": 'Evening Grosbeak', "scientific": 'Coccothraustes vespertinus', "fact": 'Its huge pale bill is powerful enough to crush large seeds with ease.'},
    {"name": 'Common Redpoll', "scientific": 'Acanthis flammea', "fact": 'Tiny flocks survive Arctic winters by feeding intensively on small seeds.'},
    {"name": 'Red Crossbill', "scientific": 'Loxia curvirostra', "fact": 'The crossed bill tips act like specialised forceps for prying seeds from conifer cones.'},
    {"name": 'White-winged Crossbill', "scientific": 'Loxia leucoptera', "fact": 'Its crossed bill lets it exploit cone crops even during extremely cold northern winters.'},
    {"name": 'Eurasian Bullfinch', "scientific": 'Pyrrhula pyrrhula', "fact": 'Males have a soft rose-red breast contrasting with a black cap and grey back.'},
    {"name": 'Azores Bullfinch', "scientific": 'Pyrrhula murina', "fact": 'Once close to extinction, it survives only on the island of São Miguel in the Azores.'},
    {"name": 'Common Chaffinch', "scientific": 'Fringilla coelebs', "fact": 'Males in different regions can develop recognisable local song dialects.'},
    {"name": 'Brambling', "scientific": 'Fringilla montifringilla', "fact": 'Winter flocks can sometimes gather in enormous numbers at rich beech-mast feeding sites.'},
    {"name": 'Snow Bunting', "scientific": 'Plectrophenax nivalis', "fact": 'It breeds farther north than almost any other land bird.'},
    {"name": 'Lapland Longspur', "scientific": 'Calcarius lapponicus', "fact": 'Breeding males transform from subtle winter plumage into bold black, chestnut and white.'},
    {"name": 'Yellow Cardinal', "scientific": 'Gubernatrix cristata', "fact": 'Despite its name, this endangered South American songbird is not a true cardinal.'},
    {"name": 'Northern Cardinal', "scientific": 'Cardinalis cardinalis', "fact": 'Both sexes sing, unusual among many familiar temperate-zone songbirds.'},
    {"name": 'Pyrrhuloxia', "scientific": 'Cardinalis sinuatus', "fact": 'Its thick yellow bill and grey-red plumage give it a desert-adapted cardinal look.'},
    {"name": 'Rose-breasted Grosbeak', "scientific": 'Pheucticus ludovicianus', "fact": 'Males wear a vivid red triangular breast patch against black-and-white plumage.'},
    {"name": 'Black-headed Grosbeak', "scientific": 'Pheucticus melanocephalus', "fact": 'Its large bill handles hard seeds but it also eats insects and fruit.'},
    {"name": 'Dickcissel', "scientific": 'Spiza americana', "fact": "Its name imitates the rhythm of the male's repeated breeding song."},
    {"name": 'Bobolink', "scientific": 'Dolichonyx oryzivorus', "fact": 'It makes one of the longest migrations of any North American songbird, reaching southern South America.'},
    {"name": 'Red-winged Blackbird', "scientific": 'Agelaius phoeniceus', "fact": 'Males flash scarlet-and-yellow shoulder patches while defending marsh territories.'},
    {"name": 'Yellow-headed Blackbird', "scientific": 'Xanthocephalus xanthocephalus', "fact": 'Its bright yellow head sits on a glossy black body, with males producing wonderfully harsh calls.'},
    {"name": 'Baltimore Oriole', "scientific": 'Icterus galbula', "fact": 'It weaves a deep hanging pouch nest from fibres suspended at the tips of branches.'},
    {"name": 'Montezuma Oropendola', "scientific": 'Psarocolius montezuma', "fact": 'Males perform dramatic bowing displays while making strange bubbling, gurgling calls.'},
    {"name": 'Crested Oropendola', "scientific": 'Psarocolius decumanus', "fact": 'Colonies hang long woven nests together from tall trees like oversized pendulums.'},
    {"name": 'Venezuelan Troupial', "scientific": 'Icterus icterus', "fact": 'It often takes over nests built by other birds rather than constructing its own.'},
    {"name": 'Scarlet-rumped Cacique', "scientific": 'Cacicus uropygialis', "fact": 'Its hanging woven nests are often clustered together in conspicuous colonies.'},
    {"name": 'Common Grackle', "scientific": 'Quiscalus quiscula', "fact": 'Its iridescent plumage can flash purple, blue and bronze despite appearing black from afar.'},
    {"name": 'Great-tailed Grackle', "scientific": 'Quiscalus mexicanus', "fact": 'Males use an enormous keel-shaped tail in conspicuous strutting displays.'},
    {"name": 'Boat-tailed Grackle', "scientific": 'Quiscalus major', "fact": 'Males and females differ dramatically in colour, with glossy black males and brown females.'},
    {"name": 'Brown-headed Cowbird', "scientific": 'Molothrus ater', "fact": "It lays eggs in other birds' nests, leaving foster parents to raise its chicks."},
    {"name": 'Orchard Oriole', "scientific": 'Icterus spurius', "fact": 'Adult males are deep chestnut and black rather than the bright orange of many orioles.'},
    {"name": 'Red-crested Cardinal', "scientific": 'Paroaria coronata', "fact": 'Despite its common name and bright red head, it belongs to the tanager family.'},
    {"name": 'Yellow-billed Cardinal', "scientific": 'Paroaria capitata', "fact": 'Its red head, black throat and yellow bill make this South American bird instantly recognisable.'},
    {"name": 'Red-cowled Cardinal', "scientific": 'Paroaria dominicana', "fact": 'A vivid scarlet hood contrasts sharply with a clean white body and dark back.'},
    {"name": 'White-eared Sibia', "scientific": 'Heterophasia auricularis', "fact": 'Its bold white ear patch and long tail make it a distinctive mountain-forest bird of Taiwan.'},
    {"name": 'Silver-eared Mesia', "scientific": 'Leiothrix argentauris', "fact": 'Yellow, orange, black and silver combine in one tiny, highly social Asian songbird.'},
    {"name": 'Red-billed Leiothrix', "scientific": 'Leiothrix lutea', "fact": "Its colourful plumage earned it the old cage-bird name 'Pekin robin', despite not being a robin."},
    {"name": 'Blue-winged Minla', "scientific": 'Actinodura cyanouroptera', "fact": 'Its patterned blue wing panels contrast with a warm brown body in Himalayan forests.'},
    {"name": 'Chestnut-tailed Minla', "scientific": 'Actinodura strigula', "fact": 'This social mountain bird wears intricate chestnut, yellow and black patterning.'},
    {"name": 'Black-crowned Barwing', "scientific": 'Actinodura sodangorum', "fact": 'Its wings and tail carry neat barring that gives the genus its English name.'},
    {"name": 'Greater Necklaced Laughingthrush', "scientific": 'Pterorhinus pectoralis', "fact": 'A bold black necklace crosses its pale chest, and flocks can be extremely noisy.'},
    {"name": 'White-crested Laughingthrush', "scientific": 'Garrulax leucolophus', "fact": 'Its shaggy white crest and loud group calls make flocks hard to miss.'},
    {"name": 'Blue-crowned Laughingthrush', "scientific": 'Pterorhinus courtoisi', "fact": "This striking blue-headed species is among the world's most threatened laughingthrushes."},
    {"name": 'Black-throated Laughingthrush', "scientific": 'Pterorhinus chinensis', "fact": 'Its dark throat and contrasting pale cheek patch give it a masked appearance.'},
    {"name": 'Common Green Magpie', "scientific": 'Cissa chinensis', "fact": 'Its brilliant green feathers can fade towards blue after prolonged exposure to light.'},
    {"name": 'Javan Green Magpie', "scientific": 'Cissa thalassina', "fact": 'This vivid green-and-red corvid is critically endangered and restricted to Java.'},
    {"name": 'Bornean Green Magpie', "scientific": 'Cissa jefferyi', "fact": 'Its luminous green body and red bill stand out in the misty forests of Borneo.'},
    {"name": 'Crested Shrikejay', "scientific": 'Platylophus galericulatus', "fact": 'A tall black crest and reddish-brown body give this Southeast Asian bird a gothic look.'},
    {"name": 'Black-crowned Tchagra', "scientific": 'Tchagra senegalus', "fact": 'It often sings from dense cover despite its bold black crown and chestnut wings.'},
    {"name": 'Crimson-breasted Shrike', "scientific": 'Laniarius atrococcineus', "fact": 'Its vivid crimson underparts contrast with glossy black upperparts in southern African scrub.'},
    {"name": 'Southern Boubou', "scientific": 'Laniarius ferrugineus', "fact": 'Pairs often perform precisely coordinated duets, sounding like one complex singer.'},
    {"name": 'Pied Avocet', "scientific": 'Recurvirostra avosetta', "fact": 'Its extraordinarily slender upcurved bill sweeps from side to side through shallow water to find small prey.'},
    {"name": 'Yellow-crowned Gonolek', "scientific": 'Laniarius barbarus', "fact": "Its brilliant red, yellow and black plumage makes it one of West Africa's showiest bushshrikes."},
    {"name": 'Common Fiscal', "scientific": 'Lanius collaris', "fact": 'Like other shrikes, it may impale prey on thorns or barbed wire for later eating.'},
    {"name": 'Great Grey Shrike', "scientific": 'Lanius excubitor', "fact": 'It is a songbird that behaves like a miniature raptor, hunting rodents and small birds.'},
    {"name": 'Loggerhead Shrike', "scientific": 'Lanius ludovicianus', "fact": 'Without powerful raptor feet, it uses thorns and wire to anchor prey while tearing it apart.'},
    {"name": 'Long-tailed Shrike', "scientific": 'Lanius schach', "fact": 'Its long black tail and bold facial mask give it a particularly dramatic silhouette.'},
    {"name": 'White-crowned Shrike', "scientific": 'Eurocephalus anguitimens', "fact": 'Small groups cooperate socially and are often seen perched together in open woodland.'},
    {"name": 'White Helmetshrike', "scientific": 'Prionops plumatus', "fact": 'Its bright yellow eye wattles and fluffy white crest make flocks look wonderfully eccentric.'},
    {"name": "Retz's Helmetshrike", "scientific": 'Prionops retzii', "fact": 'A vivid red eye ring stands out against glossy dark plumage.'},
    {"name": 'African Paradise-Flycatcher', "scientific": 'Terpsiphone viridis', "fact": 'Some males grow spectacularly long central tail feathers that stream behind them in flight.'},
    {"name": 'Indian Paradise-Flycatcher', "scientific": 'Terpsiphone paradisi', "fact": 'Adult males can occur in striking white or chestnut forms, both with very long tails.'},
    {"name": 'Japanese Paradise-Flycatcher', "scientific": 'Terpsiphone atrocaudata', "fact": 'Its elongated tail and glossy dark head make this migratory forest bird especially elegant.'},
    {"name": 'Black-necked Stilt', "scientific": 'Himantopus mexicanus', "fact": 'Its impossibly long pink legs let it wade through shallow wetlands while delicately picking prey from the water.'},
    {"name": 'Black-naped Monarch', "scientific": 'Hypothymis azurea', "fact": 'Adult males have luminous blue plumage with a neat black patch on the nape.'},
    {"name": 'Spectacled Monarch', "scientific": 'Symposiachrus trivirgatus', "fact": 'A dark facial mask contrasts with bright orange-rufous underparts and blue-grey upperparts.'},
    {"name": 'Magpie-lark', "scientific": 'Grallina cyanoleuca', "fact": 'Pairs often sing antiphonal duets, rapidly alternating notes with remarkable precision.'},
    {"name": 'Willie Wagtail', "scientific": 'Rhipidura leucophrys', "fact": 'It constantly fans and swings its tail while darting after insects.'},
    {"name": 'Rufous Fantail', "scientific": 'Rhipidura rufifrons', "fact": 'Its rounded tail spreads into a beautiful fan during quick, twisting flights through foliage.'},
    {"name": 'New Zealand Fantail', "scientific": 'Rhipidura fuliginosa', "fact": 'Its energetic tail-fanning may help flush insects into the air where they can be caught.'},
    {"name": 'Grey Fantail', "scientific": 'Rhipidura albiscapa', "fact": 'It performs restless aerial loops around branches while keeping its broad tail constantly moving.'},
    {"name": 'Spangled Drongo', "scientific": 'Dicrurus bracteatus', "fact": 'Its glossy black feathers are spangled with blue-green iridescence and its tail is deeply forked.'},
    {"name": 'Dollarbird', "scientific": 'Eurystomus orientalis', "fact": 'A pale circular patch on each wing resembles a silver coin during flight.'},
    {"name": 'Lilac-breasted Roller', "scientific": 'Coracias caudatus', "fact": 'Its plumage includes lilac, turquoise, green, blue and rust, especially vivid in bright sun.'},
    {"name": 'European Roller', "scientific": 'Coracias garrulus', "fact": 'During courtship it performs rolling, twisting display flights that inspired its English name.'},
    {"name": 'Indian Roller', "scientific": 'Coracias benghalensis', "fact": 'Its apparently brownish perched plumage erupts into brilliant blue when the wings open.'},
    {"name": 'Abyssinian Roller', "scientific": 'Coracias abyssinicus', "fact": 'Long outer tail streamers trail behind vivid turquoise-blue wings.'},
    {"name": 'Purple Roller', "scientific": 'Coracias naevius', "fact": 'Its mottled purple-brown plumage is subtler than many rollers but equally distinctive up close.'},
    {"name": 'Broad-billed Roller', "scientific": 'Eurystomus glaucurus', "fact": 'It catches large flying insects from exposed perches and has a broad, brightly coloured bill.'},
    {"name": 'European Bee-eater', "scientific": 'Merops apiaster', "fact": "It removes a bee's sting by repeatedly rubbing the insect against a perch before swallowing it."},
    {"name": 'Northern Carmine Bee-eater', "scientific": 'Merops nubicus', "fact": 'Huge colonies excavate nesting tunnels into vertical riverbanks and sandy cliffs.'},
    {"name": 'Southern Carmine Bee-eater', "scientific": 'Merops nubicoides', "fact": 'Its intense carmine plumage can turn large breeding colonies into a wall of red.'},
    {"name": 'Blue-cheeked Bee-eater', "scientific": 'Merops persicus', "fact": 'Long central tail feathers and turquoise facial patches give it an elegant profile.'},
    {"name": 'Rainbow Bee-eater', "scientific": 'Merops ornatus', "fact": "Australia's only bee-eater migrates long distances and nests in tunnels dug into sandy ground."},
    {"name": 'White-fronted Bee-eater', "scientific": 'Merops bullockoides', "fact": 'It lives in complex social groups where non-breeding relatives may help raise chicks.'},
    {"name": 'Little Bee-eater', "scientific": 'Merops pusillus', "fact": 'Despite its tiny size, it has the classic bee-eater combination of bright colours and a black eye-mask.'},
    {"name": 'Red-throated Bee-eater', "scientific": 'Merops bulocki', "fact": 'A vivid red throat contrasts with green wings and turquoise-blue facial markings.'},
    {"name": 'Turquoise-browed Motmot', "scientific": 'Eumomota superciliosa', "fact": 'Its tail feathers end in racket-shaped tips created partly by natural feather wear.'},
    {"name": 'Blue-crowned Motmot', "scientific": 'Momotus coeruliceps', "fact": 'Motmots may swing their racket-tipped tails from side to side when alarmed.'},
    {"name": 'Whooping Motmot', "scientific": 'Momotus subrufescens', "fact": 'Its resonant call carries through tropical forest while the bird often sits remarkably still.'},
    {"name": 'Tody Motmot', "scientific": 'Hylomanes momotula', "fact": 'Unlike its larger relatives, this tiny motmot lacks the famous racket-tipped tail.'},
    {"name": 'Cuban Tody', "scientific": 'Todus multicolor', "fact": 'This tiny jewel-like bird has a green back, red throat and pinkish flanks.'},
    {"name": 'Puerto Rican Tody', "scientific": 'Todus mexicanus', "fact": 'It excavates a surprisingly long nesting burrow in an earthen bank despite being only about 11 cm long.'},
    {"name": 'Jamaican Tody', "scientific": 'Todus todus', "fact": 'Its broad flattened bill helps it snatch tiny insects from the undersides of leaves.'},
    {"name": 'Broad-billed Tody', "scientific": 'Todus subulatus', "fact": 'It combines a bright green back with a scarlet throat and unusually broad bill.'},
    {"name": 'Narrow-billed Tody', "scientific": 'Todus angustirostris', "fact": 'This tiny Dominican Republic endemic often hunts insects in dense mountain vegetation.'},
    {"name": 'Belted Kingfisher', "scientific": 'Megaceryle alcyon', "fact": 'It hovers over water before plunging headfirst after fish.'},
    {"name": 'Giant Kingfisher', "scientific": 'Megaceryle maxima', "fact": "Africa's largest kingfisher can tackle surprisingly large fish and aquatic prey."},
    {"name": 'Pied Kingfisher', "scientific": 'Ceryle rudis', "fact": 'It can hover almost motionless above water before diving vertically for fish.'},
    {"name": 'White-throated Kingfisher', "scientific": 'Halcyon smyrnensis', "fact": 'Despite the name, it often hunts insects, reptiles and small vertebrates far from water.'},
    {"name": 'Stork-billed Kingfisher', "scientific": 'Pelargopsis capensis', "fact": 'Its enormous red bill is powerful enough to handle crabs, frogs and sizeable fish.'},
    {"name": 'Black-capped Kingfisher', "scientific": 'Halcyon pileata', "fact": 'A vivid blue back, purple body and red bill make this Asian kingfisher exceptionally colourful.'},
    {"name": 'Malachite Kingfisher', "scientific": 'Corythornis cristatus', "fact": 'Its tiny body is topped with a crest streaked in brilliant electric blue.'},
    {"name": 'Oriental Dwarf Kingfisher', "scientific": 'Ceyx erithaca', "fact": 'This tiny forest kingfisher combines orange, lilac, blue and pink-red in astonishingly bright plumage.'},
    {"name": 'Rufous-backed Dwarf-Kingfisher', "scientific": 'Ceyx rufidorsa', "fact": 'Its miniature size and glowing orange-red back make it look almost jewel-like.'},
    {"name": 'Common Paradise-Kingfisher', "scientific": 'Tanysiptera galatea', "fact": 'Long white tail streamers end in spatulate tips and trail behind the bird through forest.'},
    {"name": 'Buff-breasted Paradise-Kingfisher', "scientific": 'Tanysiptera sylvia', "fact": 'Its elongated white tail feathers contrast with a blue crown and warm buff breast.'},
    {"name": 'Sacred Kingfisher', "scientific": 'Todiramphus sanctus', "fact": 'It migrates across parts of Australasia and often hunts on land as well as near water.'},
    {"name": 'Collared Kingfisher', "scientific": 'Todiramphus chloris', "fact": 'This adaptable turquoise-and-white kingfisher occurs from mangroves to gardens across a huge range.'},
    {"name": 'Laughing Falcon', "scientific": 'Herpetotheres cachinnans', "fact": 'Its loud laughing call rings through tropical America, and snakes form an important part of its diet.'},
    {"name": 'Crested Caracara', "scientific": 'Caracara plancus', "fact": 'Unlike many falcons, it spends much of its time walking on the ground while scavenging and hunting.'},
    {"name": 'Northern Crested Caracara', "scientific": 'Caracara cheriway', "fact": 'It is unusually terrestrial for a falcon relative and often strides confidently across open ground.'},
    {"name": 'Peregrine Falcon', "scientific": 'Falco peregrinus', "fact": 'In a hunting dive it can exceed 300 km/h, making it the fastest animal measured in powered descent.'},
    {"name": 'Gyrfalcon', "scientific": 'Falco rusticolus', "fact": "The world's largest falcon occurs in colour forms ranging from dark grey to almost pure white."},
    {"name": 'American Kestrel', "scientific": 'Falco sparverius', "fact": 'This tiny falcon can hover over fields while searching for insects and small vertebrates.'},
    {"name": 'Lanner Falcon', "scientific": 'Falco biarmicus', "fact": 'Pairs may hunt cooperatively, with one bird flushing prey towards the other.'},
    {"name": 'Merlin', "scientific": 'Falco columbarius', "fact": 'This compact falcon specialises in fast aerial pursuits of small birds.'},
    {"name": 'Red-footed Falcon', "scientific": 'Falco vespertinus', "fact": 'Adult males are slate-grey with striking red feet and reddish under-tail feathers.'},
    {"name": "Eleonora's Falcon", "scientific": 'Falco eleonorae', "fact": 'It times breeding unusually late so migrating songbirds provide abundant food for its chicks.'},
    {"name": 'Bat Falcon', "scientific": 'Falco rufigularis', "fact": 'It often hunts at dawn and dusk, catching birds and bats in rapid flight.'},
    {"name": 'Aplomado Falcon', "scientific": 'Falco femoralis', "fact": 'Its long legs and bold facial pattern give it a distinctive, almost harrier-like appearance.'},
    {"name": 'African Pygmy Falcon', "scientific": 'Polihierax semitorquatus', "fact": "Africa's smallest raptor sometimes uses the enormous communal nests of sociable weavers."},
    {"name": 'Great Blue Heron', "scientific": 'Ardea herodias', "fact": 'This huge heron can stand motionless at the water edge before striking with its long dagger-like bill.'},
    {"name": 'Black-thighed Falconet', "scientific": 'Microhierax fringillarius', "fact": "One of the world's smallest raptors, it hunts insects and small birds from exposed perches."},
    {"name": 'Philippine Falconet', "scientific": 'Microhierax erythrogenys', "fact": 'This miniature falcon is small enough to look almost songbird-sized.'},
    {"name": 'Osprey', "scientific": 'Pandion haliaetus', "fact": 'Its reversible outer toe helps it grip slippery fish with two toes facing forwards and two backwards.'},
    {"name": 'Bald Eagle', "scientific": 'Haliaeetus leucocephalus', "fact": 'It often steals fish from other birds rather than catching every meal itself.'},
    {"name": "Steller's Sea-Eagle", "scientific": 'Haliaeetus pelagicus', "fact": 'This enormous eagle has a massive yellow bill and bold white shoulder patches.'},
    {"name": 'African Fish-Eagle', "scientific": 'Icthyophaga vocifer', "fact": 'Its ringing call is one of the most recognisable sounds of African lakes and rivers.'},
    {"name": 'White-bellied Sea-Eagle', "scientific": 'Icthyophaga leucogaster', "fact": 'Its broad wings allow long soaring patrols above coasts, estuaries and large rivers.'},
    {"name": 'Golden Eagle', "scientific": 'Aquila chrysaetos', "fact": 'Its powerful feet can seize prey ranging from rabbits to much larger mammals.'},
    {"name": 'Martial Eagle', "scientific": 'Polemaetus bellicosus', "fact": "One of Africa's largest eagles, it can take prey as large as small antelope."},
    {"name": 'Crowned Eagle', "scientific": 'Stephanoaetus coronatus', "fact": 'Its exceptionally powerful legs are adapted for hunting monkeys and other forest mammals.'},
    {"name": 'Philippine Eagle', "scientific": 'Pithecophaga jefferyi', "fact": "Its shaggy crest and enormous bill make it one of the world's most imposing forest eagles."},
    {"name": 'Wedge-tailed Eagle', "scientific": 'Aquila audax', "fact": "Australia's largest bird of prey has a distinctive long, wedge-shaped tail."},
    {"name": 'Black-and-chestnut Eagle', "scientific": 'Spizaetus isidori', "fact": 'Its striking black-and-chestnut plumage belongs to a rare eagle of Andean cloud forests.'},
    {"name": 'Ornate Hawk-Eagle', "scientific": 'Spizaetus ornatus', "fact": 'A long pointed crest and barred plumage give this tropical forest raptor a dramatic appearance.'},
    {"name": 'Changeable Hawk-Eagle', "scientific": 'Nisaetus cirrhatus', "fact": "Individuals vary greatly in plumage, which explains the English name 'changeable'."},
    {"name": 'Black Hawk-Eagle', "scientific": 'Spizaetus tyrannus', "fact": 'Its piercing whistle can reveal the bird long before its dark shape is seen above rainforest.'},
    {"name": 'Bateleur', "scientific": 'Terathopius ecaudatus', "fact": 'Its extremely short tail and long wings create a distinctive rocking flight silhouette.'},
    {"name": 'Black-winged Kite', "scientific": 'Elanus caeruleus', "fact": 'It can hover over grassland while scanning for rodents, almost like a large kestrel.'},
    {"name": 'Swallow-tailed Kite', "scientific": 'Elanoides forficatus', "fact": 'Its deeply forked tail twists constantly as it performs exceptionally graceful aerial turns.'},
    {"name": 'Snail Kite', "scientific": 'Rostrhamus sociabilis', "fact": 'Its slender hooked bill is specialised for extracting apple snails from their shells.'},
    {"name": 'Mississippi Kite', "scientific": 'Ictinia mississippiensis', "fact": 'It catches large insects on the wing and may eat them while still flying.'},
    {"name": 'Red Kite', "scientific": 'Milvus milvus', "fact": 'Its deeply forked tail works like a rudder as it circles effortlessly over the landscape.'},
    {"name": 'Black Kite', "scientific": 'Milvus migrans', "fact": "Among the world's most widespread raptors, it readily exploits carrion and human food waste."},
    {"name": 'Roseate Spoonbill', "scientific": 'Platalea ajaja', "fact": 'Its broad spoon-shaped bill sweeps through shallow water while its plumage can become spectacularly pink.'},
    {"name": 'Egyptian Vulture', "scientific": 'Neophron percnopterus', "fact": 'It is one of the few birds known to use stones as tools to crack open large eggs.'},
    {"name": 'King Vulture', "scientific": 'Sarcoramphus papa', "fact": 'Its colourful bare head can show orange, yellow, red, purple and blue skin.'},
    {"name": 'California Condor', "scientific": 'Gymnogyps californianus', "fact": 'A conservation programme brought this giant scavenger back from only 27 surviving birds in 1987.'},
    {"name": 'Turkey Vulture', "scientific": 'Cathartes aura', "fact": 'It has an unusually strong sense of smell and can locate carrion hidden beneath forest canopy.'},
]

LEAP_DAY_BIRD = {
    "name": "Magnificent Frigatebird",
    "scientific": "Fregata magnificens",
    "fact": "Courting males inflate a huge scarlet throat pouch like a shiny red balloon.",
}


def get_bird_of_the_day(day: date):
    """Return one stable bird for a date, with every list bird used once per ordinary year."""
    if day.month == 2 and day.day == 29:
        return LEAP_DAY_BIRD

    # Shuffle once per year, deterministically. A fixed salt avoids depending on
    # Python's process-randomised hash() implementation.
    shuffled = BIRDS.copy()
    rng = random.Random(731_000 + day.year)
    rng.shuffle(shuffled)

    # Convert day-of-year to a 0..364 index, removing leap day from dates after Feb 29.
    index = day.timetuple().tm_yday - 1
    if day.year % 4 == 0 and (day.year % 100 != 0 or day.year % 400 == 0) and day.month > 2:
        index -= 1

    return shuffled[index]
